# wrangler.toml
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "d1-demo-prod-db"
database_id = "88009640-3bb6-41cc-ac11-6c83fe80bf0c"
preview_database_id = "DB"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "d1-demo-preview-db"
database_id = "f333689e-ab31-41ab-8d0b-2c5c37a09f17"

